"""The wire contract OBS shares with the rest of the tripbot streaming system.

OBS is fed by the per-platform MediaMTX relay (RTSP dashcam feed, published
into by playout) and onscreens (browser-source overlays), and each OBS instance
talks to the relay/onscreens of its OWN platform (obs-twitch → mediamtx-twitch /
onscreens-twitch).

Service names and ports come from contract.json, generated by tripbot's
`pkg/contract` and synced into this repo via `task contract:sync`. Never
hand-edit contract.json here — change the Go constants and re-sync.
"""

from __future__ import annotations

import json
from pathlib import Path

_CONTRACT_FILE = Path(__file__).resolve().parents[1] / "contract.json"

with _CONTRACT_FILE.open() as _f:
    _CONTRACT = json.load(_f)

_SERVICES: dict[str, str] = _CONTRACT["services"]
_PORTS: dict[str, int] = _CONTRACT["ports"]

# OBS's own container/service ports, in the order the Deployment + Service list
# them. The k8s port *names* are local (nothing outside this repo refers to
# them); the numbers are the contract's.
PORTS: list[tuple[str, int]] = [
    ("vnc", _PORTS["obs_vnc"]),
    ("websocket", _PORTS["obs_websocket"]),
    ("novnc", _PORTS["obs_novnc"]),
    ("obs-server", _PORTS["obs_server"]),
]
NOVNC_PORT = _PORTS["obs_novnc"]

# The per-platform MediaMTX relay. Hand-declared: the relay is the infra repo's
# construct and no generated contract carries its name or port yet.
_MEDIAMTX_RTSP_PORT = 8554


def dashcam_rtsp_url(platform: str) -> str:
    return f"rtsp://mediamtx-{platform}:{_MEDIAMTX_RTSP_PORT}/dashcam"


def onscreens_url_base(platform: str) -> str:
    return f"http://{_SERVICES[f'onscreens_{platform}']}:{_PORTS['onscreens_http']}"
